
server:
  port: 8085

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

    listener:
      simple:
        default-requeue-rejected: false

  profiles:
    active: prod

  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"