
server:
  port: 8085

spring:
  application:
    name: notification-service

  Profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8086/

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

    listener:
      simple:
        default-requeue-rejected: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"