server:
  port: 8086

spring:
  application:
    name: config-server

  profiles:
    active: git
#    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abhinandan9285/eventcart-config.git
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5
#        native:
#          search-locations: file:///D://distributed-order-platform-config
#          search-locations: classpath:/config

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

encrypt:
  key: 343SDFG44T221533DSSADFE3E

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"